apiVersion: v1
kind: Service
metadata:
  name: busyboxcurl
spec:
  replicas: 3
  containers:
  - name: slurm
    image: radial/busyboxplus:curl
    imagePullPolicy: IfNotPresent
  dnsPolicy: ClusterFirst
  restartPolicy: Always