kind: PersistentVolume
apiVersion: v1
metadata:
  name: slurm-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/gluster/k8s-pv/slurm_config"
