apiVersion: v1
kind: Pod
metadata:
  name: slurm-client-dev
  labels:
    name: sclient-dev
spec:
  containers:
  - image: hub.tek-pi.com/env/slurm-client-dev:latest
    name: slurm-client-dev
    command: [ "/bin/bash", "-c" ]
    args:
    - source /mnt/gluster/qinglong/cluster.dev/cycleserver.py;
      while true; do
      sleep 3600;
      done;
    ports:
    - containerPort: 22
    - containerPort: 8888
    volumeMounts:
    - mountPath: /etc/slurm-llnl
      name: slurm-config
    - mountPath: /opt/spack
      name: spack
    - mountPath: /mnt/gluster
      name: data
  volumes:
  - name: slurm-config
    hostPath:
      path: /mnt/gluster/k8s-pv/slurm-config
      type: Directory
  - name: spack
    hostPath:
      path: /mnt/nfs/spack
      type: Directory
  - name: data
    hostPath:
      path: /mnt/gluster
      type: Directory
