apiVersion: v1
kind: Service
metadata:
  name: slurm-ctrl
spec:
  ports:
  - port: 7321
    targetPort: 7321
    name: scheduler
  - port: 6817
    targetPort: 6817
    name: slurmctld
  - port: 6818
    targetPort: 6818
    name: slurmd 
  selector:
    app: slurm-ctrl