FROM ubuntu:16.04
MAINTAINER Tsinglung Tseng <tsinglung.tseng@gmail.com>

# 1COPY . /container
# RUN /container/build.sh

#ENV LANG="en_US.UTF-8" \
#    LANGUAGE="en_US:en" \
#    LC_ALL="en_US.UTF-8"

RUN apt-get update && apt-get install -y apache2 vim


#ENTRYPOINT ["/container/tool/run"]


