apiVersion: v1
kind: Pod
metadata:
  name: slurm-ctrl
    labels:
    name: sctrl
spec:
  nodeName: cs0
  #hostNetwork: true
  containers:
  - image: hub.tek-pi.com/env/slurm-ctrl:latest
    name: slurm-ctrl
    command: [ "/bin/bash", "-c" ]
    args: 
    - /etc/profile.d/startup.sh;
    ports:
    - containerPort: 7321
      containerPort: 6817
      containerPort: 6818
    volumeMounts:
    - mountPath: /etc/slurm-llnl
      name: slurm-config
    - mountPath: /opt/spack
      name: spack
    - mountPath: /home/data
      name: data
  volumes:
  - name: slurm-config
    hostPath: 
      path: /mnt/gluster/k8s-pv/slurm-config
      type: Directory
  - name: spack
    hostPath:
      path: /mnt/nfs/spack
      type: Directory
  - name: data
    hostPath:
      path: /mnt/gluster/k8s-pv/data
      type: Directory
