apiVersion: v1
kind: Pod
metadata:
  name: slurm-client
spec:
  nodeName: cs0
  #hostNetwork: true
  containers:
  - image: hub.tech-pi.com/env/slurm-client:latest
    name: slurm-client
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - mountPath: /etc/slurm-llnl
      name: slurm-config
    - mountPath: /opt/spack
      name: spack
    - mountPath: /home/data
      name: data
  volumes:
  - name: slurm-config
    hostPath: 
      path: /mnt/gluster/k8s-pv/slurm-config
      type: Directory
  - name: spack
    hostPath:
      path: /mnt/nfs/spack
      type: Directory
  - name: data
    hostPath:
      path: /mnt/gluster/k8s-pv/data
      type: Directory