apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"cluster0.tek-pi.com": ["192.168.1.185"]}
  upstreamNameservers: |
    ["8.8.8.8", "8.8.4.4"]
