apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"server.local": ["192.168.1.185"]}
  upstreamNameservers: |
    ["180.168.255.118", "8.8.4.4"]
